### ISSUE TITLE
Why orm.MyModel selectors don't update?

### ISSUE THREAD

**Issue by ConneXNL** [tommikaikkonen/redux-orm#11]
Given the following code:

```
export const ormSelector = state => state.orm;
export const getReviews = createSelector(
    ormSelector,
    schema.createSelector((orm) => {
        console.log("This is not hit on second run even if state changed...");
        return orm.Review;
    })
);
```

For some reason whenever the state changes the getReviews(state) is not hit a second time and you will end up with an outdated state.

Whereas calling the following selector:

```
export const getAllReviews = createSelector(
    ormSelector,
    schema.createSelector((orm) => {
        return orm.Review.all();
    })
);
```

updates the result of getReviews(state).

Is this intended? Should we always suffix with .all() when we want to work with a Model?

The problem is that the orm.Review.all() does not contain functions like withId()...

**Comment by tommikaikkonen** [comment]
The selector memoization works by looking at which model states you accessed inside the selector. In the first case, that's the function `orm => orm.Review`. That doesn't record any model state accesses, because it only gets the Model class, so the selector isn't rerun. When the other selector function calls `orm.Review.all()`, the Review model is recorded as being accessed, and therefore on subsequent calls of the selector, an identity check (`===`) is done on the current and previous `Review` model state to determine if the selector should be rerun.

I'd say your options depend on what kind of abstractions you've built around your selectors. If you have some complex logic that doesn't make the required model state accesses for the proper memoization to happen, you can wrap that logic in a normal function

```javascript
const getReview = orm => orm.Review;
```

And use that function in the concrete selector that does the accessing.
```javascript
const getAllReviews = createSelector(
    ormSelector,
    schema.createSelector(orm => {
        return getReview(orm).all();
    });
)
```

You could use something like `pipe` from `ramda` or `lodash` to make the selector definition nicer there (`schema.createSelector(pipe(getReview, Review => Review.all()))`)

Adding a `withId` or `get` method to a QuerySet might be worthwhile, though.

**Comment by ConneXNL** [comment]
Thanks for the response. I found out the problem myself later that day. 

However, I am still a little confused on what the preferred way is to query the orm with withId() from for example a non-orm reducer. Since schema.createSelector((orm) => orm.Review;}) is not really the way to go. 

What is the preferred way to access orm.Review bound to the current state?

If I am always to use all() then I think a withId and get on the QuerySet would definitely be a nice feature but as long as withId() on a QuerySet wouldn't require a loop trough the entire collection.

**Comment by dimatter** [comment]
`
exports.allPackages = schema.createSelector((orm) => {
  return orm.Package.all().toRefArray()
    })
`

subsequent Package.create`s from inside the reducer do not trigger an update. 
What gives?

**Comment by tommikaikkonen** [comment]
@ConneXNL a `withId` for a QuerySet without looping through the items in the QuerySet needs some further thinking. The QuerySet currently keeps an internal array of the model instance id's that it holds. `QuerySet.withId` could access the correct object in O(1) by delegating to `Model.withId`, but to check that the object actually belongs to the QuerySet we need to loop through the id's in the QuerySet internal array, which is O(N), albeit a fast O(N) since we're only comparing integers or strings, equal to `Array.prototype.includes`.

Keeping a hash index in the QuerySet would help. This makes QuerySet's internal state look very much like the serialized database presentation Redux-ORM uses (one that includes an object of `{id: entity}` and an array of `[...ids]`). I haven't decided what the right way to go about that is yet. If we added the hash index, a QuerySet could be thought of as a subset `Model` with similar internal structure, and that might have implications for a lot of the internals.

I believe backend ORMs handle a chained "withId" (e.g. `Model.objects.filter(deleted=False).get(pk=1)` in Django) easily because they're lazy. The resulting query would probably be executed by the database by first looking up the object with the specific id (`pk=1`), and then running the filters (`deleted=False`) to see if that object should returned. Redux-ORM is not lazy, so it doesn't know which filters were run previously, only the resulting id array from that filter. Another solution to the problem would be to make QuerySets lazy.

As to your problem, I'm not sure what the culprit is. It seems like the selector is being called with `undefined` state at some point if `nextState` is `undefined`. If you like you can post a larger piece of the code and a stack trace and I'll try to see what's up.

**Comment by tommikaikkonen** [comment]
@dimatter that's odd, the selector looks right. To make sure the problem is not in the selector, please try this:

```javascript
exports.allPackages = schema.createSelector(orm => {
    const returnValue = orm.Package.all().toRefArray();
    console.log(orm.accessedModels); // Should log ['Package']
    return returnValue;
})
```

If it successfully logs `['Package']`, the problem might be elsewhere. If not, to debug you might want to switch the `allPackages` selector for a normal function that accepts the ORM state object, and inspect that the updates are visible in the object. If they are, and the selector doesn't work, that's a bug and I'll look into it.

**Comment by diffcunha** [comment]
I'm having the same issue as @dimatter but only when I set `idAttribute` on the model with some other prop, for instance: `'name'`.

Here is my selector:

```js
export const ormSelector = state => state.orm

export const wallets = createSelector(
  ormSelector,
  schema.createSelector(orm => {
    const data = orm.Wallet.all().toRefArray()
    console.log(orm.accessedModels) // It logs ['Wallet']
    return data
  })
)
```
In sum:
- When I don't set `idAttribute`, the selector updates after `Wallet.create(...)`
- When I set `idAttribute`, the selector doesn't update anymore

**Comment by diffcunha** [comment]
I found the problem. See #37
