### ISSUE TITLE
Similarities with redux-schema?

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#13]
I recently noticed a new project called https://github.com/ddsol/redux-schema, and it seems to have some similarities with redux-orm.  I asked the author of redux-schema what his thoughts were (https://github.com/ddsol/redux-schema/issues/1), and I'm curious what your takeaway is as well.

**Comment by tommikaikkonen** [comment]
Nice to see a different permutation on the problem. My takeaway from a glance is pretty similar to @ddsol, looks like `redux-schema` takes over a bigger part of redux by returning a modified store, and taking over the action creator and reducer responsibilities, whereas `redux-orm` gives you a way to define reducers and selectors alongside any other business logic you execute through Redux. 

**Here are my current thoughts on the problem topic of related data in Redux**. In a general sense, `redux-orm` and `redux-schema` are hacks. Hacks that are very useful and needed, because the Redux reducer architecture does not conform easily to interrelated data. When reducers need info from sibling reducers, we come up with all kinds of hacks, such as

- querying data in the action creator and putting it in the action object to keep reducers pure, or
- making the reducer control a bigger slice of state, or
- passing relevant state down to child reducers as an extra argument.

You know what would eliminate these hacks? A proper immutable database on the front-end. Switch the Redux state object for a database where you can specify mutations and queries declaratively, like SQL or Datalog. Action creators return update statements, perhaps using a nested select statement that specifies some value used in the update. No reducers, since the database knows what to do based on the update statement you gave it. Selectors are just query statements. Relationships between data are acknowledged by the database.

If you're programming in functional style, the declarative update and select statements go well with the paradigm. With OO programming, you could use the statements or build an ORM around that database.

But building a proper database is no small feat. The thing with using JavaScript functions to update data (i.e. reducers) is that you can do anything, no matter how simple or complex. That's what enables Redux to be such a tiny library. A database needs to implement a complex query language that can handle all those complex cases, and handle them in a performant way.

In Redux, and on the web generally, you store both business state and UI state. UI state goes well with a Redux-like composition where there are no interdependencies between slices of state. Business state with relationships does not. The combination of keeping business state and UI state in the same place is convenient but it's more difficult for a single database to support both well.

One project that has taken on the feat of a front-end database is [datascript](https://github.com/tonsky/datascript). I really like that it lets you specify updates and queries with data. That would make it really easy to test. And the query language is very expressive. However, the interoperability with pure JavaScript puts me off currently, as you need to write the queries as EDN strings instead of data using JavaScript built-ins. Also, the datomic/datascript database has some [performance tradeoffs](https://github.com/tonsky/datascript/issues/130) given its expressive query language. 

[`lovefield`](https://github.com/google/lovefield) is a SQL database on the front-end, but it's not immutable. Maybe an immutable version of that would be feasible. Or maybe an immutable database with a query language that is works specifically for the web, similar in syntax to GraphQL.

I believe the overall trend is that as front-end apps get more complex, front-end databases will become more and more viable. We just need a good immutable one!

**Comment by markerikson** [comment]
Thanks for the very detailed answer.

I've certainly observed that the use of relational data inside of Redux definitely does trend towards becoming an actual "immutable database".  On which note, I ran across https://github.com/brandonbloom/jseg recently, which looks like it may sorta be along those lines.

Also, I agree with your thoughts on Datascript.  The concept is interesting, but while it may be "usable" from Javascript, the current API is not particularly JS-friendly.

**Comment by plandem** [comment]
Well, the reason i decided to try 'redux-orm', because i already implemented 'fast-hack' for almost same, but with plain JS objects and at current stage it's still possible to switch for something other. I was think to refactor and use ImmutableJS Records, but found your solution that's already more solid, than mine.

So looks like everyone tried to make own version that solves same problems :) Maybe time to unite :)

**Comment by Elijen** [comment]
Great response @tommikaikkonen, 

What do you think would be the ideal state for complex front end apps with heavy business logic? Would that be a performant DB (doing indexing and lookups) + ORM layer (making it easy to manage relationships) + API layer (syncing data with server) for the business logic and Redux for UI state (Redux would probably use the DB layer via redux-thunk or similar)?

I am still trying to find the right mindset for implementing large-scale apps.

**Comment by tommikaikkonen** [comment]
@Elijen, I think the ideal state depends on the project. An array of objects goes a long way in JS. When everything is already in memory, looping through 50-100 objects for querying or copying an array of the same length occasionally is not too slow. People developed complex apps back when Backbone came out.

For front-end, an important factor is whether the app is mainly offline or online. With the latter, it's possible to leave the front-end state simple and do the heavy lifting on the backend. This saves reimplementing business logic in two places. But it's not always possible.

Maintaining write-side business logic on the frontend is not too hard with larger datasets without a DB, but for queries you start needing indexes on more than just the primary keys. A common case is a user sorting a list. An index on the sort column will make that operation on a list of 200 objects snappy versus an O(N) full scan or a backend call. But no one wants to maintain custom indexes when you have proper database systems to do that! It would bring an order of magnitude more complexity. In these cases using a DB can bring a lot of value but it's very uncommon for people to do that.

Your description is one possibility of the structure for a non-trivial app. An ORM is not always needed if the DB handles relationships natively, Redux is not the only sane state management pattern, etc.

I wouldn't look for a single ideal solution, but I think there's a lot to explore in improving state management from non-trivial apps! :)
