### ISSUE TITLE
feature request - import prepared state

### ISSUE THREAD

**Issue by plandem** [tommikaikkonen/redux-orm#15]
Well, we have quite a lot of data for one dataset - about 1.8Mb(18K entities) of quite simple JSON, like:
```
[
...
{id:2, parent_id:1, title: 'aaaaa'}
...
]
```

Right now, after fetching request to API i import it at reducer like:
```
      action.records.forEach(record => {
        if(model.hasId(record[idAttr])) {
          model.withId(record[idAttr]).update(record);
        } else {
          model.create(record);
        }
      });

      const nextState = session.getNextState();
      return {
        ...state, 
        [name]: nextState,
        $api: {...state.$api, [action.hash]: action.records.length }
      };
```

and it takes toooooo much time. I would like to have a fast way of merging two state internally, not via models. I'm ready to prepare valid shape of 'chunk' for raw import.

if data already exists, i would like to replace it to speed-up.

**Comment by plandem** [comment]
here is profile info:
https://www.dropbox.com/s/d9lmegl9lrt2fi9/Screenshot%202016-04-22%2019.24.55.png?dl=0

**Comment by tommikaikkonen** [comment]
Currently, a large amount of objects is not where Redux-ORM shines. There are some easy picking for performance optimizations, though.

A big part of the slowness is because Redux-ORM doesn't utilize mutative operations in sessions yet. I.e. we only care about immutability between two `getNextState()` return values, operations on new objects created between those two can be mutated, but currently we copy objects even though we could apply mutative operations on them. For large N, this can get really slow, as you saw.

So, before Redux-ORM applies transient mutations where possible, for a temporary workaround, the best one for your case would be to transform your fetched data to the same form that Redux-ORM stores in Redux, and apply a manual deep merge to the current state (with `lodash` or similar), totally bypassing Redux-ORM when you're loading a large number of objects.

Another possibility is to use `schema.withMutations` or instantiate a Session with the `withMutations` flag set to True. In this case you need to be sure you can apply mutations, so a deep copy of the state is probably necessary. Then you can batch load a big set of data and no objects will be redundantly copied.

The solution to the underlying problem here is to modify the [Backend](https://github.com/tommikaikkonen/redux-orm/blob/master/src/Backend.js) class to selectively apply mutative operations to objects that have been created during the current session. I created a utility library [`immutable-ops`](https://github.com/tommikaikkonen/immutable-ops) a while back to do exactly what Backend needs but haven't gotten around to refactoring it to use it yet. I'll try to get a version out within a week since your use case desperately needs it :)

**Comment by markerikson** [comment]
In my current prototype application, whenever I load a project's contents from the server I want to completely replace any existing data I had on the client.  I have a `createInitialState()` function that fills in a couple constant items that always need to exist, and for my `loadProjectContents()` reducer, I just use the result of that as the starting point for parsing my data, like this:

```js
export function createInitialState() {
    const defaultState = schema.getDefaultState();
    const session = schema.from(defaultState);

    // Create some items that must always exist

    const initialState = session.reduce();
    return initialState;
}

export function loadProjectContents(state, action) {
    const {payload} = action;
    const newState = createInitialState();

    const session = schema.withMutations(newState);
    
    // parse my incoming data from the action

    return newState;
}
```

**Comment by plandem** [comment]
@markerikson, well....in my case i can't load full project context, because some parts can be huge and we need on request anyway.

@tommikaikkonen i will try something from it.

**Comment by plandem** [comment]
is it ok?
```
/**
 * Root reducer for ORM that supports multi schemas.
 * Also process successful responses from API with records to import as models of schema.
 */
export default function(state = initialState, action) {
  if (action.schema) {
    const { name, schema } = action.schema;
    const ormReducer = schema.reducer();
    let ormCurrentState = state[name];
  
    if(action.type === ORM_API_RESPONSE && Array.isArray(action.records) && action.model) {
      const session = schema.withMutations(ormCurrentState);
      const model = session[action.model];
      const idAttr = model.idAttribute;

      console.log(`<<< [${name}:${action.model}] import...`);
      action.records.forEach(record => {
        if(model.hasId(record[idAttr])) {
          model.withId(record[idAttr]).update(record);
        } else {
          model.create(record);
        }
      });

      const nextState = session.getNextState();
      
      return {
        ...state, 
        [name]: {...nextState, [action.model]: {...nextState[action.model]}},
        $api: {...state.$api, [action.hash]: action.records.length }
      };
    } else {
      console.log(`<<< [${name}] reduce...`);
      return { 
        ...state, 
        [name]: ormReducer(ormCurrentState, action) 
      };
    }
  }

  return state;
}
```

**Comment by tommikaikkonen** [comment]
@plandem new release 0.8.1 has the batched mutation feature. That would considerably cut the load time. From my tests, previous implementation took 15s to load 10000 objects, now it's about 0.5s. Let me know if you still encounter problems with that.

**Comment by plandem** [comment]
ok, i will test it later.
