### ISSUE TITLE
[Feature Request]Allow fk receive function as argument

### ISSUE THREAD

**Issue by NE-SmallTown** [tommikaikkonen/redux-orm#162]
Currently we just allow string as argument of `fk(...)`, but thinking this scenario, the fetch response return an object which has two properties named `entityId: 123` and `type: foo`, it means the type maps to one Model, e.g. `() => { if (type === 'foo') return 'ModelFoo' }`. And the `123` means the model's id.

So to be a summary, it makes that we can use 
```
  fk(
    () => { if (type === 'foo') return 'ModelFoo' }, 
    () => { if (type === 'bar') return 'correspondingRelationNameInModelBar' }
  )
```

**Comment by haveyaseen** [comment]
Looks out of scope to me. The fields need to be present when you register the models to the ORM so that it can set up many-to-many through models etc. So if you want to register the models asynchronously, then you can also set `fk()` fields asynchronously on your model classes. It's approximately the same level of difficulty.
```javascript
registerModelsAsynchronously(orm) {
    const models = ... // collect models from somewhere
    models.forEach(model => {
        model.fields = {
            whatever: fk({ to: whateverType })
        };
    });
    orm.register(models);
}
```
