### ISSUE TITLE
Duck support?

### ISSUE THREAD

**Issue by husek** [tommikaikkonen/redux-orm#17]
Just wondering how it goes with Duck ( https://github.com/erikras/ducks-modular-redux )?

As far as i can see, the Store it's inside ORM, and Ducks use a decoupled Store.

**Comment by markerikson** [comment]
Uh... no, no, no.

Ducks are merely an approach for file organization for your actions and reducers - putting related actions and reducers into one file rather than potentially three separate files (actions file, constants file, reducers file).  There's no "decoupled store" or anything.  If you look at the example in that Ducks README, you see that since a duck should `export default function theReducer()`, you just import your duck reducers and hook them up into your app.

You can use Redux-ORM in two main ways: either define reducers per-model class and hook the generated combined reducer up to your main reducer, or use Redux-ORM as a helper/abstraction library inside of your own reducer logic.  

So, overall, your reducer setup might look like:

```js
import {combineReducers, createStore} from "redux";

import duckReducer1 from "./duck1";
import duckReducer2 from "./duck2";
import schema from './schema';
import myCustomReducerThatUsesORM from "./myCustomReducer";

const mainReducer = combineReducers({
    duck1 : duckReducer1,
    duck2 : duckReducer2,
    entities : schema.reducer(),
    otherReducer : myCustomReducerThatUsesORM
});

const store = createStore(mainReducer);
```

No interference with ducks at all.
