### ISSUE TITLE
[Question] Reducer Best Practice

### ISSUE THREAD

**Issue by tihuan** [tommikaikkonen/redux-orm#175]
Do you define a reducer for each Model or a generic reducer that listens to all events and do multi-model updates for each action?

For example:
```js
case CREATE_AUTHOR_AND_A_BOOK {
  Author.create({ ... })
  Book.create({ ... })
}
```

vs.

```js
class Author extends Model {
  reducer() {
    ...
    case CREATE_AUTHOR_AND_A_BOOK {
      Author.create({ ... })
    }
  }
}

class Book extends Model {
  reducer() {
    ...
    case CREATE_AUTHOR_AND_A_BOOK {
      Book.create({ ... })
    }
  }
}
```

The documentation seems to recommend having a generic reducer over model specific reducer now. Just wanted to see what you guys think 😁

**Comment by markerikson** [comment]
Yes, I would recommend using Redux-ORM within your own reducer logic, rather than attaching reducers to your model classes.  Both are possible, though.

I personally have written some pretty generic "entity update" code that can handle CRUD operations for any of my model types.  See http://blog.isquaredsoftware.com/2017/01/practical-redux-part-7-forms-editing-reducers/#creating-a-generic-entity-update-reducer for an example.

**Comment by tihuan** [comment]
Hi Mark! Thanks so much for your quick response! Ah, really appreciate the article :D Will read it now!

**Comment by tihuan** [comment]
Read the articles :D Super useful! Thanks so much again!
