### ISSUE TITLE
[question] Cachable/concurrent way to load data into redux-orm?

### ISSUE THREAD

**Issue by aksonov** [tommikaikkonen/redux-orm#18]
Sorry, my question may be unrelated to this component, but finally i have found suitable component to store my data inside app, thanks!

I have the model where Message contains Profile (i.e. sender), Profile contains Image (avatar). Also I have various Profile Lists of Profile IDs and need to display it nicely within react native. With redux-orm i could finally manage/display this data, the only question is how to fetch it. I can't use Falcor/Relay because data is fetched from xmpp server, so it is completely different datasources.

The only way i see now is to use redux-saga or redux-side-effects to fetch data and then load that data to red-orm via actions... Or maybe to make some enhancement to your library to allow load data to it, what are your thoughts?

**Comment by tommikaikkonen** [comment]
The common way to do that in Redux is to fetch the data in an action creator or use redux-side-effects/redux-saga, normalize it if needed, pass data on to reducers and persist it to the store. For Redux-ORM, instead of a normal reducer, you can have a routine that takes each item you want to save as a "table row" and passes that to `Model.create(row)` for each Model you've defined in your schema. You could do that in the Model reducers themselves or start a custom session in your root reducer, or even do all that before starting the Redux lifecycle and pass a loaded state to the Redux store.

**Comment by aksonov** [comment]
Thanks for answer! I've tried all redux ways, thunk, sagas and effects and all they (as well as redux itself) have a lot of boilerplate. I'm trying now to make my data sources as FRP event streams and eliminate redux completely via react combinators:
https://github.com/milankinen/react-combinators

however i'm still hoping to use redux-orm to manage model, looks like it doesn't have direct dependency from redux.
