### ISSUE TITLE
Managing ordering of children?

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#19]
Scenario: Class Parent hasMany Child.  I've got a Parent instance with its list of children, as parsed from my backend data.  The ordering of those children is important, but is not based on any inherent property (names are arbitrary, child IDs are effectively GUIDs).  That said, my server-side Child model does actually have a "sequenceId" field that I update, although I think the way my server logic and my previous app's client logic worked, that didn't actually matter get used much.

I need to be able to insert a new child before or after a given child, as well as re-order children within the list.  At the moment, I'm not seeing any obvious way to use Redux-ORM to do that.  I see that `QuerySet` has an `orderedBy()` function, but that appears to be more for doing ordering within that QuerySet.  I also see that a many-relationed QuerySet is given an `add()` function, but that appears to pretty much just add to the "end" of the list.

Is there any straightforward way to manage ordering of children?  One hypothetical workaround might involve "deleting" all children, followed by "re-adding" them in the right order, but that seems awfully complicated.  

Any suggestions appreciated.

**Comment by tommikaikkonen** [comment]
Hmm, I think generally in relational databases, you save an order key in the table you want to maintain an order for. Since you can't derive that from data, you store the order in a new column such as `order`. Then in queries you order the result by that order key.

You can use JavaScript numbers as floats to store that. [Here's an SQL SO answer related to that](http://stackoverflow.com/a/13675332).

E.g. You start with two rows, assign them sort keys `0` and `1`. If you want to insert a record between them, you give it a sort key of `(0 + 1) / 2 === 0.5`. On the ends you could increment or decrement by one. When you want to update the order for the whole list, you assign new sort keys for each one. The danger is that you insert in the same place multiple times and the float precision runs out, depending on your data you might have to handle that case.

If your schema works by a Child having a foreign key `fk` to parent, you would save the order key in the Child table.

If you're using a many-to-many relations `many` then you need to make an explicit through model that has the order key (Redux-ORM makes a basic through model implicitly, but it doesn't support custom through models with additional fields yet).

To make an explicit through table, you remove the `many` field declaration, create a new through model e.g. `ParentChild` with fields `parent`, `child` and `order` (Redux-ORM implicit through-models only have `parent` and `child` field). For now you'll lack the ability to do `parent.children.all()` type of queries, and instead have to do `const childIds = ParentChild.filter({ parent: parentId }).orderedBy('order').withRefs.map(item => item.child)` and work from there.

**Comment by Aryk** [comment]
I thought I remember seeing somewhere that there were through models support now in Redux orm, but I can't seem to find it anymore? Does that functionality exist?

**Comment by markerikson** [comment]
Yeah, it's going to be in 0.9.  #39 was the original attempt at adding them, and the 0.9 PR at #62 says that functionality will be included.

**Comment by tommikaikkonen** [comment]
Yes, it exists in `0.9`, but I haven't had time to write about it in the README.md. If you generate the API reference with `make build` you'll see the docstring for `many` that includes instructions how to use it, or just look at the docstring here:

https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/fields.js#L330

**Comment by Aryk** [comment]
Great, thanks!

**Comment by chanan** [comment]
@Aryk Have you gotten ordering working? I can't seem to figure out how to get it working with the M2M custom through class, and changing everything to fk is painful.

**Comment by Aryk** [comment]
hey @chanan , i don't use through classes yet. I actually created a method on the children class that then queries the rest. So something like:

book.pages.queryItems() 

and then that will return a filterset. I find it being a little more explicit, even though its a little more verbose than just "book.pageItems()".

But I will probably look into "through" eventually, just hasn't been a huge problem. This is not like an orm in front of DB that has to joins efficiently for performance reasons.

**Comment by ernsheong** [comment]
@haveyaseen what's the way to achieve this today?
