### ISSUE TITLE
Question - Further relationship information (through model) how to

### ISSUE THREAD

**Issue by lilbumblebear** [tommikaikkonen/redux-orm#211]
I have been able to successfully create many-to-many relationships between several models, but I am struggling with a many-to-many relationship that uses a custom through model.   Similar to  #34 I have additional fields I would like to attach to a relationship.  

I am struggling with how to format my data so that an upsert/create works correctly and assigns the additional information to the through model?

**model 1 - Product**
```
Product.fields = {
    suppliers: many("Supplier"),
};
```
**model 2 - Supplier** - no fields just attributes

If I only care about linking product to supplier, with no additional information I can do something like this:
` Product.upsert({id: 1, name: "product name", suppliers: [1,2,3]})
`

But, if I have a custom through model and want to have additional information like cost associated to the product-supplier link this doesn't work:

**model 1 - Product**
```
Product.fields = {
    suppliers: many({
        to: 'Supplier',
        through: 'Product2Supplier',
    }),
};
```
**model 2 - Supplier** - no fields just attributes

**model 3 - Product2Supplier**
```
Product2Supplier.fields = {
    product: fk("Product"),
    supplier: fk("Supplier"),
};
```

Neither 
` Product.upsert({id: 1, name: "product name", suppliers: [{id:1,cost: 25.00},{id:2,cost:10}]})
` 
nor
` Product.upsert({id: 1, name: "product name", suppliers: [{supplier:1,cost: 25.00},{id:2,cost:10}]})
`

work, instead, in the Product2Supplier model the supplier key gets set to the object ex: supplier: {supplier:1,cost: 25.00}

**What is the correct way to structure the data so that I can create/upsert a model with a relationship and additional fields via a custom through model?**

**Comment by haveyaseen** [comment]
Hi @lilbumblebear, it looks like this is not possible using `create`, `update` or `upsert`.
Basically what happens is that `Model._refreshMany2Many` is called to update the `suppliers` field. This method however assumes that you pass an array of supplier IDs instead of objects.

I suggest you do something like the following:
```javascript
Product.upsert({id: 1, name: "product name", suppliers: [1, 2]});
// the following can be part of a different reducer and/or react to a different action
Product2Supplier.filter({product: 1, supplier: 1}).toModelArray().map(product2supplier => {
  product2supplier.update({cost: 25.0});
Product2Supplier.filter({product: 1, supplier: 2}).toModelArray().map(product2supplier => {
  product2supplier.update({cost: 10});
});
```
In fact, you will only be able to access the additional fields on `Product2Supplier` by interacting with the model directly, not through `product.supplierSet` or `supplier.productSet`. (To change these names pass a `relatedName` to `many`, e.g. `suppliers: many({to: 'Supplier', relatedName: 'products', through: `Product2Supllier`}`.)

Your use-case is clear to me, though, and we should put this on our roadmap (#140). Further, through models should be indexed by both `throughFields` (in this case`product` and `supplier`).  This is

**Comment by lilbumblebear** [comment]
Thank you @haveyaseen, I was already doing something similar to what you mentioned, but was hoping that I was being obtuse and missing something much easier.   I appreciate the fast response!

**Comment by markerikson** [comment]
I think the lookup logic could be _slightly_ simplified to something like:

```js
const product2Supplier = Product2Suppler.filter({product: 1, supplier: 1}).first();
product2Supplier.update({cost: 25.0});
```

**Comment by haveyaseen** [comment]
Yep! Or even
```javascript
const product2Supplier = Product2Supplier.get({product: 1, supplier: 1});
product2Supplier.update({cost: 25.0});
```
