### ISSUE TITLE
[Question] Is it ok to return "ModelArray" from selectors?

### ISSUE THREAD

**Issue by Eddie-CooRo** [tommikaikkonen/redux-orm#239]
According to the documentation when we use createSelector, we should return the ref to the object instead of its model.
Why is that? is there any performance downside with returning models & modelArrays?

**Comment by Eddie-CooRo** [comment]
I use models to have access to relations not modifying them.
Does it affect performance?

**Comment by haveyaseen** [comment]
This is not necessarily an issue of Flux at all.

Using models will always be less performant than using refs directly. This is fairly obvious when you look at these code snippets:
https://github.com/tommikaikkonen/redux-orm/blob/4f055aa7ac0d166563ebe7757b7979808a16fa90/src/QuerySet.js#L77-L79
https://github.com/tommikaikkonen/redux-orm/blob/4f055aa7ac0d166563ebe7757b7979808a16fa90/src/QuerySet.js#L85-L90
https://github.com/tommikaikkonen/redux-orm/blob/4f055aa7ac0d166563ebe7757b7979808a16fa90/src/Model.js#L70-L93
Essentially, when your queries return large arrays you will incur a performance penalty because each item needs to first be wrapped in a new `Model` instance which will cause all of its fields to be copied over. The more fields your models have the higher the penalty.

That might however be all there is to it. Concurrency should normally not be an issue because of the `Session` concept  and its transaction logic, so I'm not sure if there can be any race conditions. Other than if you mutate the state directly, which should be possible with both refs and model instances.

**Comment by haveyaseen** [comment]
You should only use models as long as you don't care that their references change. Especially with React this is an anti-pattern because all dependent components need to re-render not only when your selector is re-run, but also when the model instances themselves did not change. Using model instances directly defeats the purpose of per-instance memoization.

An example:
```javascript
const getBooks = createSelector(
    orm,
    state => state.orm,
    session => session.Book.all().toModelArray()
);
function mapStateToProps(state) {
    return {
        books: getBooks(state),
    };
}
function BookList({ books }) => {
    console.log("re-rendering each time that ANY book changes");
    return (
        <ul>
            {books.map(book => (
                <Book
                    key={book.id}
                    book={book}
                />
            )}
        </ul>
    );
}
function Book({ book }) => {
    console.log("ALSO re-rendering each time that ANY book changes");
    return (
        <li>{book.title} written by {book.author}</li>
    );
}
```
