### ISSUE TITLE
Unknown plugin `transform-runtime`

### ISSUE THREAD

**Issue by otiai10** [tommikaikkonen/redux-orm#24]
# Problem As Is

In project of usage side

```
TransformError: /Users/otiai10/project/foo/node_modules/redux-orm/lib/index.js: Unknown plugin "transform-runtime" specified in "/Users/otiai10/project/foo/node_modules/redux-orm/.babelrc" at 0, attempted to resolve relative to "/Users/otiai10/project/foo/node_modules/redux-orm"
```

# Reason

It's because missing plugins (and presets as well) in node_modules of the project.

Of course it can be solved by hitting following command in the project of usage side.

```
npm install babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2
```

# Solution To Be

But, it's a bit weird for npm to describe the dependencies of library in the package.json of usage side.
So I think we should put these dependencies in `dependencies` field of package.json, not in `devDependencies`. like this

```diff
diff --git a/package.json b/package.json
index b0bf608..c788783 100644
--- a/package.json
+++ b/package.json
@@ -21,9 +21,6 @@
     "babel-cli": "^6.8.0",
     "babel-core": "^6.7.7",
     "babel-eslint": "^6.0.4",
-    "babel-plugin-transform-runtime": "^6.8.0",
-    "babel-preset-es2015": "^6.6.0",
-    "babel-preset-stage-2": "^6.5.0",
     "babel-register": "^6.8.0",
     "chai": "^3.0.0",
     "deep-freeze": "0.0.1",
@@ -41,6 +38,9 @@
     "babel-runtime": "^6.6.1",
     "immutable-ops": "^0.4.2",
     "lodash": "^4.12.0",
+    "babel-plugin-transform-runtime": "^6.8.0",
+    "babel-preset-es2015": "^6.6.0",
+    "babel-preset-stage-2": "^6.5.0",
     "reselect": "^2.0.1"
   }
 }
```

**Comment by tommikaikkonen** [comment]
Thank you for opening the issue. Sorry for the delay, I was on a trip for a couple of weeks.

I tried to reproduce your issue but I'm having trouble. It seems like Babel is trying to compile the library files, even though it's been already compiled?

The `redux-orm` build process uses Babel plugins and presets to generate ES5 to the `lib` folder, which is the code that is imported when users require `redux-orm` in their own projects. `babel-plugin-transform-runtime` adds requires and calls to the `babel-runtime` library instead of inlining the code. So in the `lib` folder, the only remaining dependency from Babel should be `babel-runtime`. You can verify that by going to the `redux-orm` folder in the `node_modules` folder of your project and looking at the files.

`babel-runtime` is already in the `dependencies` in `package.json`. There should be no need to add the presets and `babel-plugin-transform-runtime` to dependencies. I don't know how you arrived at that error.

I just updated [redux-orm-primer](https://github.com/tommikaikkonen/redux-orm-primer) with the latest version of `redux-orm`. If you try cloning that, and running

```
npm install
npm run start
```

Do you get an error?

**Comment by otiai10** [comment]
Thank you very much, and I hope your trip was great.

> It seems like Babel is trying to compile the library files, even though it's been already compiled?

hmm, I have 1 thing I can imagine. Probably, this is because I'm using `react-native`, and it executes compiling **with running**.

And your redux-orm-primer works well. Thank you very much and it's very good to know for me.

**Comment by kevando** [comment]
Hey @otiai10 what did you do to get orm working with react-native? I cant seem to get past these same babel errors

**Comment by kevando** [comment]
I am not familiar with Babel, so still struggling here.

**Comment by otiai10** [comment]
@kevando Hi, how about it?
```
npm install babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2
```

**Comment by hckhanh** [comment]
Please keep in mine that `babel-plugin-transform-runtime` is only used for Development. If you want to use for Production, use `babel-runtime`.
Refer: https://babeljs.io/docs/plugins/transform-runtime/

**Comment by henrymoulton** [comment]
This issue is still occurring when using React Native with Expo. The above advice works for me on version 0.9.4. But later versions of redux-orm have a different Babel setup see PR #206
