### ISSUE TITLE
Path to 1.0.0

### ISSUE THREAD

**Issue by joeporpeglia** [tommikaikkonen/redux-orm#27]
Hey! Really awesome work here man. No issues, just a question about the future of the project. We're looking into redux orm as a crucial piece of our front end framework, so I'm curious what your ideas are for a v1 release, or maybe why you wouldn't consider the current state viable.

**Comment by markerikson** [comment]
So just to toss in my own two cents as an evaluation: I've probably been the biggest proponent of `redux-orm` so far.  Tried it out right after it was first published, talked with @tommikaikkonen quite a bit about features and use cases, pasted the link into a few dozen comment threads, etc.  And, it's been working great so far in my own app.  

I'm maybe using it a bit differently than some of the "suggested" approaches.  Rather than defining reducers in my Model classes, I'm basically using it as a sort of advanced set of "selector" functions in my reducers, my thunks, and my `mapState` functions.  I'm also using it for its immutable update abilities in my reducers as well.  

There's a whole bunch of other libs that try to put some kind of OOP layer on top of Redux, but most of them start taking Redux in a pretty significantly different direction.  `redux-orm`, on the other hand, keeps itself limited enough to some very useful behavior for managing normalized data in your store.

So yes, I'd absolutely say it's a viable usable tool to work with at this point.

**Comment by tommikaikkonen** [comment]
Thanks for the vote of confidence @markerikson :)

I'd say the reason the version is `0.x` instead of `1.x` is the limited feature set compared to ORMs in general, not the stability or quality of the code. As you assess your options, you'll also want to read [my thoughts on on related data in Redux in general](https://github.com/tommikaikkonen/redux-orm/issues/13#issuecomment-211129281).

Due to the smaller feature set, the "database" abstraction is not perfect. If the abstraction doesn't offer what you need, it can be hard to achieve it without a bunch of hackery. Otherwise it should be enjoyable to work with.

Based on the GitHub issues I've received, here are the current big pain points:

- Do you want to store order of elements? Add a column the specifies the order value, but each query will do O(n) lookups without the ability to put an index on that column.
- When deleting a model, do you want the related models to be deleted too? Current deletion strategy is just `SET_NULL`, no support for `CASCADE`.
- Do you want custom through models in many-to-many relationships? You need operate with a manual through model.

Based on those pain points the todo list is:
- add ability to add indexes on columns (other than the ID, which is indexed by default)
- add `CASCADE` deletion strategy and
- add custom through models.

Perhaps after those features, a `1.0` would be in order. As to when they'll be done, I can't promise anything. Help in the form of pull requests is always welcome and I'll happily review them.

**Comment by markerikson** [comment]
Boy, that list of pain points sounds.... familiar :)

FWIW, using my own field for ordering, implementing my own "update a Model instance from another instance" logic, and implementing my own cascaded delete logic has worked out great for me so far.  Got past my mental block and been able to crank along on features the last couple weeks.

Also, one other related note.  I've had several places where I need to do a fairly large update as part of one overall step, but it requires a number of smaller updates in the process.  These updates also tend to be dependent on each other.  (Example: recursing upwards through a tree of data, where each parent's current checked/unchecked/partially-checked state has to be calculated based on its immediate children.)  `redux-orm`'s queued updates are great for being non-destructive, but don't lend themselves to that iterative process.  My original implementation of the checkbox logic actually hacked around things by reading the current Session's pending update queue, which is a horrible approach.  
You _could_ also call `session.reduce()` and create a new Session from the new data, but that seemed a bit painful and redundant.

I finally figured out that a Session instance just does lots of lookups for its current `this.state` variable.  So, I could actually just do `session.state = session.reduce()`, swap out the old state tree with the new state tree, and still have the current "session-bound classes" work.  That's made my multi-step updates reasonably nicer, I've just had to comment the approach to clarify what I'm doing.

Maybe worth adding something like that as a built-in operation?

**Comment by orecus** [comment]
@markerikson I've just started using Redux-Orm and finding that I'm having a similar problem to what you are talking about. I hope it's ok to ask in here, otherwise i can create a seperate issue for this. 

In my case I'm loading records and their relations from the backend, and I want to loop over them to both create the item itself, and its relation.

But it does not seem to work due to the queued nature, could you share some additional details on how you solved it with `session.state = session.reduce()`?

My action looks something like this;

```js
      case ADMIN_LOAD_DEPARTMENTS_SUCCESS:
        const departments = action.payload.data;

        departments.forEach(function(department) {
          Department.create(department);
          if (department.DepartmentId != undefined) { Department.withId(department.DepartmentId).children.add(department.id); }
        });
        break;
```

**Comment by markerikson** [comment]
@orecus : a Session instance is really just a facade over a plain JS object (which could actually come from anywhere, not just from your Redux state).  If I do `const value = someModel.someRelation.someField`, Redux-ORM will look up the related model when the `someRelation` property is accessed, and then look up the `someField` value in the underlying JS object when the `someField` property is accessed. 

The current underlying object is stored as `session.state`.  Calling `session.reduce()` applies any pending updates and returns a new state value.  So, `session.state = session.reduce()` creates a new state object, and then updates the `session` instance to use that object when doing data lookups.  That means that the next time one of the Model instances from that session is accessed, the data will come from the updated object.

I actually just wrote a blog post discussing this technique and several others: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/ .

**Comment by orecus** [comment]
@markerikson Thanks for the input! Still having some issues to get things going properly with initial loading by creating and adding the relations from my backend, still doing further research to this and learning.

I could have explained the example a bit better, a department can have a relation to another department trough the DepartmentId, so what i'm doing is adding the created department as a child to another department. So DepartmentId is the "parent" department that this deparment should be a child of.

I'm looking forward to your next post and the example application, as i'm sure i could learn a thing or two from it. :) 

Footnote: My work had your blog blocked due to "Filter Avoidance" for some reason. :/

**Comment by markerikson** [comment]
Okay, that makes a bit more sense.  One possible approach might look like this:

```js
// Queue initial CREATE commands
departments.forEach(department => Department.create(department));

session.state = session.reduce();

departments.forEach(department => {
    if(department.DepartmentId !== undefined) {
        const parentDepartment = Department.withId(department.departmentId);
        // Queue UPDATE commands
        parentDepartment.children.add(department.id);
    }
});


// OPTIONAL: if using your own reducer instead of a reducer
// defined on a model class, apply updates and point Session at new data.
// Otherwise, this is done automatically.
return session.reduce();
```

FYI, I've got Part 3 in the series mostly written.  Hoping to review it tonight and publish in the next day or two.

As for the blog filtering: yeah, I think I know why.  Several years ago I had briefly set up a proxy script for some reason I can't remember, and that apparently got found by bots, then it was flagged by web filters.  Apparently those filtering tools still have my site in their databases :(

**Comment by orecus** [comment]
@markerikson Thanks! Still hitting my head here on this, but I'll create a new issue with more details instead of poluting this one with further derailment.

I'll keep my eye out for your new blog entry!

**Comment by plandem** [comment]
#140
