### ISSUE TITLE
Foreign key handling during item deletion?

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#32]
I've got some sagas that request data from the server on app startup, and I also have my app set up to hot-reload those sagas as I edit them.  Because of that, I defined my reducer structure for those cases to look like:

```js
function loadTypeAFromServer(state, action) {
export function loadRadioParts(state, action) {
    const {payload} = action;

    const session = schema.from(state);
    const {ModelTypeA} = session;

    // Clear out existing items
    ModelTypeA.all().withModels.forEach(item=> item.delete());

    // swap out data used by the session
    session.state = session.reduce();

    const {newDataEntries} = payload;
    newDataEntries.forEach(data => ModelTypeA.parse(data));

    const newState = session.reduce();
    return newState;
}
```

This _was_ working fairly well for my hot-reloading purposes, or so I thought - I'd edit my sagas, they'd reload and re-request my data, I'd clear out anything that had been loaded previously, and load up the newly requested data.

Unfortunately, I just noticed an issue.  I have another model class that references ModelTypeA using a foreign key.  When I delete the instances of ModelTypeA, I see that all of ModelTypeB's foreign key references to ModelTypeA are being wiped out and set to `null`, which is not at all what I want.

It looks like the relevant code is in `Model._onDelete()`:

```js
            } else if (field instanceof ForeignKey) {
                const relatedQs = this[key];
                if (relatedQs.exists()) {
                    relatedQs.update({ [field.relatedName]: null });
                }
```

Is that really the best way to handle deletions?  Is there a better way to handle things on the library side, or do I need to re-think how I'm doing things on the app side?

**Comment by tommikaikkonen** [comment]
Hmm. Deleting each record without setting the fields referring to that field to `null` or deleting the referring record brings the "database" to an invalid state. The foreign keys would point to unexisting rows. This is the reason that `redux-orm` doesn't outright support bypassing `_onDelete`. You do fix the situation by parsing the new models and adding them to the state, but `redux-orm` doesn't know this.

Would it be possible to do `newDataEntries.forEach(({ id, ...attrs }) => ModelTypeA.get({ id }).update(attrs))` ? Or does that mess up other relationships? It's not as fast, but since this is for hot reloading, it should be ok.

**Comment by markerikson** [comment]
Yeah, I could probably rework things to avoid the deletion/reloading aspect.  The load-data-on-startup shouldn't be changing going forward, and also the dataset should be fairly consistent, so I can probably skip the deletion process if I've got valid entries already.
