### ISSUE TITLE
Best practice for updating navigation properties and coding one-to-many relationships

### ISSUE THREAD

**Issue by david-lennox** [tommikaikkonen/redux-orm#45]
Could you please confirm that:

* Where you have a one-to-many relationship we should ONLY specify the foreign key with `fk()` and NOT specify the navigation property at the other end. For example the following is incorrect:

```js
User.fields = {
    todos: many('Todo', 'user'),
};
```

* The navigation properties are not updated automatically by the library. That is, adding a new Todo to the Todo "table" with its user field set to `someUser.id` does not result in the respective ID being added to `someUser.todos` array.

**Comment by tommikaikkonen** [comment]
This was probably left unclear in the documentation, sorry about that! You should only define a many-to-one relationship on only one side of the relationship. For example if you have the models Publisher and Book with a many (Book) to one (Publisher) relationship, you'd only define the `fk` on Book.

```
Book.fields = {
  publisher: fk('Publisher', 'books')
};
```

This allows you to access many Book models through a Publisher model instance with `Publisher.withId(someId).books`. Your problem should go away once you define the relationship on only one side.

The Pull Request #39 adds documentation to the fields; you can check that out [here](https://github.com/tommikaikkonen/redux-orm/pull/39/commits/e16ee16c3dac9e4ce13224a759c9c02bc57a99f3) (object specification and through models are not in the current release, but otherwise the documentation is valid.)
