### ISSUE TITLE
Accessing models across reducers

### ISSUE THREAD

**Issue by pronebird** [tommikaikkonen/redux-orm#57]
I use orm reducer which calls `Model.reducer` on each action. However I have another reducer that maintains UI state and one of actions is to select item in UI which is later should be fetched from orm reducer and being copied for editing. Is there any way to access orm's state from other reducers? Or how does one query models outside of orm's reducer?

I really enjoy having reducers in models for basic actions. It's great for validation too. But I don't see any way how to access models from other parts of the app.

**Comment by markerikson** [comment]
Three thoughts:

- First, I'll again point you to the articles I wrote that discuss my own approaches for using Redux-ORM, including writing my own separate reducers instead of part of the Model classes: http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/ and http://blog.isquaredsoftware.com/2016/10/practical-redux-part-2-redux-orm-concepts-and-techniques/
- Second, if you define a reducer as part of a Model class, the fourth argument to that reducer is the current Session instance.  You can retrieve references to the other Model classes as part of that Session:

```js
static reducer(state, action, ThisModelClass, session) {
    const {SomeOtherModelClass} = session;

    // do something with the other model class here
}
```

- Third, you may also want to read through the Redux FAQ entry on "sharing data between reducers" in general: http://redux.js.org/docs/faq/Reducers.html#reducers-share-state

**Comment by pronebird** [comment]
Thanks! I noticed that you have separate reducer. I read all of three blog posts. Redux FAQ and some googling brought me to rereduce which I successfully used to share orm's state with reducer used for UI editing.
