### ISSUE TITLE
Error defining multiple 1:1 fields of the same type

### ISSUE THREAD

**Issue by markerikson** [tommikaikkonen/redux-orm#6]
I've got a couple model classes that look roughly like this:

```js
class A extends Model {}

class B extends Model {
	static get fields() {
	    field1 : oneToOne("A"),
	    // field2 : oneToOne("A")
	}
}
```

If I only have a single `oneToOne("A")` entry, things seem to work okay.  However, if I uncomment the `field2` declaration, I get an error:

```
Uncaught TypeError: Cannot redefine property: a
(anonymous function) @ Schema.js:252
```

Looking at the transpiled version, it appears to be pointing to Schema.js line 219, where it defines the backwards relationship.

Just ran into this one, not sure how to resolve it.

**Comment by markerikson** [comment]
So it's been a long time since I actually took a databases class.  Is this where the "fk" descriptor would be appropriate?

**Comment by tommikaikkonen** [comment]
If your intention is to have data where many B's can point to A, then you should use `fk`. If your intention is to have only one B associated to A through a `fk`, you can use `oneToOne`. The difference is that by accessing the reverse field of a `oneToOne` you get a single model instance instead of a `QuerySet`. So given a model declaration like this:

```
class A extends Model {}
A.modelName = 'A';

class B extends Model {
    static get fields() {
        field1 : oneToOne('A'),
        field2 : fk('A')
    }
}
B.modelName = 'B'
```

You can do this in a session:

```
const b = Ainstance.b;
expect(b instanceof B).to.be.true;
const manyBs = Ainstance.bSet;
expect(b instanceof QuerySet).to.be.true;
```

When declaring a `oneToOne`, it automatically sets up a reverse field to A with the name of the model the field was declared on (B in lowercase). For a `fk`, that would be `bSet` (model name in lowercase + Set). When you set up a second `oneToOne` field, it tries to redefine that same property, which causes the error (I'll leave this issue open, because it would be useful to have a descriptive error message raised here). You can fix this by setting a manual reverse name for either or both of the fields:

```
class A extends Model {}
A.modelName = 'A';

class B extends Model {
    static get fields() {
        c: oneToOne('A', 'c'),
        d: oneToOne('A', 'd')
    }
}
B.modelName = 'B'
```

So in a session:

```
const b = Ainstance.c;
const anotherB = Ainstance.d;
```

**Comment by tommikaikkonen** [comment]
Fixed in 0.3.1 by throwing descriptive error messages in similar cases. See https://github.com/tommikaikkonen/redux-orm/commit/ca56173a92e6731155deb297e3ba005e444beb16

**Comment by markerikson** [comment]
Hmm.  Thanks for the response, but I have to say in this case the behavior seems unintuitive.  The usage pattern seems to be calling the correct relationship definition function with the name of the associated model class.  Why should I *have* to pass in an alternate field name in the case where I have multiple fields of the same type?  Why can't it reuse the same "type1Set" field on the other end?

**Comment by tommikaikkonen** [comment]
A one to one relationship in relational databases is done using a foreign key with a UNIQUE constraint. UNIQUE means that the column that defines the foreign key (in this case, `field1` and `field2`) must be unique -- no duplicates within all the values for that column in the table, except for `null`. Based on this, `field1` and `field2` in the same `B` instance can refer to the same `A` instance without violating the schema constraints. The same thing with 2 `B` instances where one refers to `someAInstance` through `field1` and the other through `field2`.

With the initial schema you posted, what we're expecting the default `AInstance.b` getter to get is the `B` instance where `{ fieldX: Ainstance.getId() };`, where X is 1 or 2. Because there are two `oneToOne` fields without custom reverse field names, we don't know what X you mean when accessing the `Ainstance.b` getter. That is why declaring those two fields fails.
