### ISSUE TITLE
Cannot install module from git

### ISSUE THREAD

**Issue by pronebird** [tommikaikkonen/redux-orm#63]
Hey,

I am trying to plug-in my fork into app and I always get 

>Module not found: Error: Cannot resolve module 'redux-orm' 

Do you happen to know what may cause that?

I am using `npm install 'https://github.com/pronebird/redux-orm.git#d6720d97125a3be6b53c5c02f01ffb2f4126bed0' --save`

```
└─┬ redux-orm@0.8.4  (git+https://github.com/pronebird/redux-orm.git#d6720d97125a3be6b53c5c02f01ffb2f4126bed0)
  ├─┬ immutable-ops@0.4.2 
  │ └── ramda@0.19.1 
  └── reselect@2.5.4
```

ll node_modules/redux-orm says:

```
drwxr-xr-x    15 pronebird  staff    510 Nov 19 18:25 .
drwxr-xr-x  1046 pronebird  staff  35564 Nov 19 18:25 ..
-rw-r--r--     1 pronebird  staff     78 Nov 19 18:25 .babelrc
-rw-r--r--     1 pronebird  staff     16 Nov 19 18:25 .eslintignore
-rw-r--r--     1 pronebird  staff    532 Nov 19 18:25 .eslintrc
-rw-r--r--     1 pronebird  staff     56 Nov 19 18:25 .jscsrc
-rw-r--r--     1 pronebird  staff     17 Nov 19 18:25 .npmignore
-rw-r--r--     1 pronebird  staff   1081 Nov 19 18:25 LICENSE
-rwxr-xr-x     1 pronebird  staff    497 Nov 19 18:25 Makefile
-rwxr-xr-x     1 pronebird  staff  26112 Nov 19 18:25 README.md
-rw-r--r--     1 pronebird  staff    764 Nov 19 18:25 gulpfile.js
-rw-r--r--     1 pronebird  staff    339 Nov 19 18:25 jsdoc.conf.json
-rw-r--r--     1 pronebird  staff  31195 Nov 19 18:25 package.json
drwxr-xr-x    15 pronebird  staff    510 Nov 19 18:25 src
-rw-r--r--     1 pronebird  staff    907 Nov 19 18:25 webpack.config.js

**Comment by tommikaikkonen** [comment]
Yes, the problem is that the `main` key in `package.json` has a value of `dist/redux-orm.js` which does not exist in the repository. That file needs to exist in the repository in order for installing from git to work.

To do that, in your own fork remove the

```
dist
```

line from `.gitignore`, build the project so that `dist/redux-orm.js` is generated, and then commit that to the repository and push. It should work after that.

I'm keeping the `dist` directory in `.gitignore` to 1) not need to build the project for each commit to master and 2) to keep the diffs clean.

**Comment by pronebird** [comment]
That worked! Thanks!
