### ISSUE TITLE
TypeError: Model.classmethod is not a function

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#66]
This very well could be my environment, but I'm only seeing this issue coming from the redux-orm library.

I'm running the latest version of typescript and I'm getting very far in the build process, so all the typechecking seems to be working, except for at the very end where I get this typeError at runtime I believe.

Basically, none of the static methods on Model are working on my subclasses.

```JS
console.log(B.foo());
// "d"
console.log(User);
// { [Function: QuerySet]
//   sharedMethods:
//     [ 'count',
//       'at',
//       'all',
//       'last',
//       'first',
//       'exists',
//       'filter',
//       'exclude',
//       'orderBy',
//       'update',
//       'delete' ] } }
console.log(Model);
// { [Function: Model]
//   fields: { id: Attribute { opts: {} } },
//   definedProperties: {},
//   virtualFields: {},
//   querySetClass:
//   { [Function: QuerySet]
//     sharedMethods:
//       [ 'count',
//         'at',
//         'all',
//         'last',
//         'first',
//         'exists',
//         'filter',
//         'exclude',
//         'orderBy',
//         'update',
//         'delete' ] } }
console.log(Model.options);
// [Function: options]
console.log(User.options);
// undefined
```

I saw this problem initially when I tried to register my models. It was calling     model.invalidateClassCache(); in `register`.

Any ideas what it could be?

**Comment by tommikaikkonen** [comment]
Per the output that you pasted, User looks to be a QuerySet instead of a Model&mdash;is that correct? If not, that's weird - the prototype of a subclass should be the superclass, which means that `options` should be defined there if `class User extends Model` works and is used correctly.

Other people using typescript have had similar problems, see #29. I would look into the compiled-to-JS code to check that the prototype of `User` is `Model` as [outlined here](http://www.2ality.com/2015/02/es6-classes-final.html#the-prototype-of-a-subclass-is-the-superclass)

**Comment by Aryk** [comment]
Yup, that's the exact issue I'm having. The output is correct, it's just what console.log outputs. There is probably something on how you are doing the exports that's causing it to joke. It's likely with the way you wrote your library since it's happening to other users and, again, seems to be emanating for your library. If I find the fix, can you merge it in?

**Comment by Aryk** [comment]
I'm going to continue this thread on #29.
