### ISSUE TITLE
is there any type checking for ID? [help needed :(]

### ISSUE THREAD

**Issue by plandem** [tommikaikkonen/redux-orm#67]
I puzzled, because i have 2 almost same structures and from redux side looks same for me, except one thing - responses from server a) ID as string, e.g. { id: "1", title: "bla"} and b) ID as integer, e.g. {id: 1, title: "bla"}

Models almost same, but for (a) i can get reverse models for many-many and for (b) i always getting empty array.

(a)
```
class User extends Model {
	toString() {
		return `User: ${this.username}`;
	}
}

User.modelName = 'User';

class UserGroup extends Model {
	toString() {
		return `UserGroup: ${this.title}`;
	}
}

UserGroup.modelName = 'UserGroup';
UserGroup.fields = {
	users: many('User', 'groups'),
};

```

and (b)
```
class Dataset extends Model {
  toString() {
    return `Dataset: ${this.title}`;
  }
}

Dataset.modelName = 'Dataset';

class DatasetTopic extends Model {
	toString() {
		return `DatasetTopic: ${this.title}`;
	}
}

DatasetTopic.modelName = 'DatasetTopic';
DatasetTopic.fields = {
	parent_id: fk('DatasetTopic', 'children'),
	datasets: many('Dataset', 'topics'),
};

```

I'm trying to get result for hours, but still no success.

this reselect works fine:
```
		console.log(`>>> [users+relations] reselect...`);
		return {
			groups: orm.UserGroup.all().toRefArray(),
			users: orm.User.all().map(user => {
				return {
					...user.ref,
					groups: user.groups.withRefs.filter(group => group).map(group => ({ id: group.id, title: group.title })),
				};
			})
		}
```

and this one is not working:
```
		console.log(`>>> [datasets+relations] reselect...`);
		return {
			groups: orm.DatasetTopic.all().toRefArray(),
			datasets: orm.Dataset.all().map(dataset => {
				return {
					...dataset.ref,
					groups: dataset.topics.withRefs.filter(group => group).map(group => ({ id: group.id, title: group.title })),
				};
			})
		}
```

**Comment by plandem** [comment]
looks like type checking exists. I force to stringify all keys and it fixes. So it's up to you now.

**Comment by tommikaikkonen** [comment]
The problem here likely is that a foreign key value and the foreign column it is pointing to are not the same types of value (string and number or vice versa), therefore the equality check fails, returning an empty array.

Thinking off the top of my head, casting all id's as strings should work for almost all cases, as long as nobody has been depending on ID values with multiple types (i.e. relying on the fact that `({ parent_id: 1 }).id !== ({ id: '1' }).id`). I would think that's very rare and probably unexpected, like in your case.

As far as I'm aware, for any two numbers `num1` and `num2`, this holds:

```javascript
(num1 === num2) === (num1.toString() === num2.toString())
```

If that's correct, this could be worthwhile to implement.

**Comment by plandem** [comment]
Well, I'm not sure:
1) speed...probably it will drop, in some cases it can be critical
2) I never pass the models directly to views, so further checking will not working in views, because in view i will have same original types.

So right I process each response from server to stringify keys(in my case server can't warrant the same types for PK/FK - in some cases we have strings, in other - numbers). That's why I'm not sure that your solution will help :(
