### ISSUE TITLE
Accessing the sessionBoundModels outside of reducer

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#69]
Maybe I'm missing something, but is there anyway to access the data from the store outside of having the store object?

That would mean, when you create the store, you would have to export the variable there and pass it around your app so you can start a redux session with orm.session(store.getState().orm).

Is that right? I currently don't have the store actually exported throughout my app, figured maybe there was a better way. The thing is, I'm trying to do an isomorphic app, so I'm actually creating the store twice, once for the server and once for the client.

**Comment by markerikson** [comment]
Ah... seems like this is much more of a Redux question?

The normal places you would need to access this data are:
- reducers (already given part or all of the store state, depending on your reducer structure)
- Extracting data for components (`mapState` is given the entire store state)
- Action creators (thunks and other middleware have access to `getState`)

**Comment by Aryk** [comment]
Thanks @markerikson. That was helpful. That's what I figured. Seems like it kind of keeps you on the rails so you don't get off the rails doing fancy stuff.

**Comment by tommikaikkonen** [comment]
Like Mark said, if you're strictly using the library with Redux, you'll want to set up a reducer that takes the orm/db state and starts up a Session from it, applies updates, and returns `session.state` at the end. And the same in a selector, except you return any results from your queries instead of the database state. I'm not sure what kind of setup you have on the backend, but I suppose you have an initial state available, from which render the initial HTML to send to the client? In that case it's best to do that with selectors, as you can then reuse the same logic on the frontend.

**Comment by Aryk** [comment]
I guess I wanted to preseed the database before I have it plugged in with my backend api (which would do the seeding then). I actually wrote a seeder that works similar to your class level reducers. Here it is for fun:

```js
const defaultSeeder = (session) => {
  session.sessionBoundModels.forEach(modelClass => {
    if (typeof modelClass.seeder === 'function') {
      modelClass.seeder(modelClass, session);
    }
  });
};

const createReducer = (orm, updater = defaultUpdater, seeder = defaultSeeder) => {
  return (state, action) => {
    let session;

    if (state) {
      session = orm.session(state);
      updater(session, action);
    } else {
      session = orm.session(orm.getEmptyState());
      seeder(session);
    }

    return session.state;
  };
};

```
