### ISSUE TITLE
Suggestion: refresh with state pass in.

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#77]
I find myself needing to this in the code once in a while. Just thought I'd share this convenience method. It makes sense that given the redux state we might want to refresh a particular model instance without needing to know whether the instance is bound to the session or not.

```js
  /**
   * Refresh the model by providing a new state.
   * @param dbState
   * @returns {Model}
   */
  public refresh(dbState) {
   this.getClass().connect(orm.session(dbState));
    this.refreshFromState();
    return this;
  }
```

Maybe there is a way to do this already, but the updates don't persist to the instance, so we need to fetch the instance again to keep things in sync sometimes.

**Comment by tommikaikkonen** [comment]
Where are you calling this method in a Redux application? In my applications, the usual lifecycle of a Model instance would start and end in a selectors, reducers, or action creators. Some people pass them off to views to read attributes, but a refresh to the view would provide a new Model instance instead of modifying the existing instance. The code indicates that you are keeping references to Model instances across state changes?

**Comment by markerikson** [comment]
Yeah, my own usage pattern is generally: create a Session, get a Model class or two, query/update, done.  Roughly the same in `mapState` functions, thunks, and reducers.  I definitely don't keep Model references around past that.

**Comment by Aryk** [comment]
Actually, I'm using them in thunks. Sometimes I call a method which modifies a record via dispatch. I could also apply those changes to the current record as well and mutate it, but I prefer to get a fresh state so I know what I'm working with. Sometimes in a thunk the dispatch is happening in a different method, and when it returns to the current method I want to know the new record, so that is where I use this.

**Comment by Aryk** [comment]
@plandem just wanted to get this on your radar. I think this would be useful for reasons I described above.

**Comment by haveyaseen** [comment]
I'll leave it at that as I don't think the Model class should be aware of the ORM or state management in general. `refreshFromState` feels very hacky already. If anyone is interested in having this functionality part of Redux-ORM, please provide an exhaustive example so that we can discuss it further.
