### ISSUE TITLE
Custom indexes

### ISSUE THREAD

**Issue by Elijen** [tommikaikkonen/redux-orm#78]
I know this feature is planned, but didn't find any PR or issue created.

As I found myself to need (a unique) custom index recently I could potentially create a PR, but would like to discuss what are the current plans and what the API should look like.

In 0.9 `attr()` was introduced with (undocumented) `opt` attribute. I guess it could be used to configure the indexing? Something like: 
```js
Model.fields = {
   email: attr({isIndex: true, isUnique: true})
};
```

For unique indexes:
```js
{
   items: [1, 2, 3],
   itemsById: {...},
   idByEmail: {
      'foo@bar.com': 1
   }
}
```

For non-unique indexes:
```js
{
   items: [1, 2, 3],
   itemsById: {...},
   idsByEmail: {
      'foo@bar.com': [1, 2]
   }
}
```

Then to fetch attributes:
```js
session.Model.findBy('email', 'foo@bar.com')
```

**Comment by tommikaikkonen** [comment]
Awesome to hear! This is something that would benefit a lot of people.

I think the `attr({ isUnique: true })` could be enough to warrant the creation of an unique index, meaning that unless `isIndex` is explicitly set, it would create an index. At least that's how Django ORM does it.

For `isIndex`, that could probably be shortened to just `index` as that communicates intent to create an index on that attribute instead of it already having one. The `index` name provides some flexibility in the future if we have multiple index types (e.g. bitmap indexes, b-trees or normal javascript objects, Maps), you could specify it with a value `{ index: 'bitmap' }`.

Given that indexes are auxiliary data structures that are not needed to reconstruct the data, it could be viable to put indexes under an unenumerable `__indexes` key or similar for each table state, so that they don't show up in debugging tools. E.g.:

```javascript
{
    items: [1, 2, 3],
    itemsById: {...},
    __indexes: {
        email: {
            'foo@bar.com': 1,
        }
    }
};
```

(Semantically, itemsById is also an index. But it's special since it's the index that actually stores records instead of id's)

Another benefit of not needing to serialize indexes is that we're free to use other data structures than the JavaScript Object. Specifically `Map` would allow to index complex values without implementing a hash function ourselves. And 3rd party data structures: bitmap indexes, b-trees, etc. That's something that doesn't need to be implemented now, but good to keep in mind when developing the first version of this.

There's some edge cases with unique indexes to be aware of. For example, what if `email` is a nullable field? In that case, you'd expect the index to handle the `undefined/null` value with many values and everything else with a single value. We can avoid this complexity by restricting unique indexes to non-nullable fields for now, but either way that needs to be clearly specified.

To use the indexes in queries, it would be best to add that to [`Table.prototype.query`](https://github.com/tommikaikkonen/redux-orm/blob/master/src/db/Table.js#L101) in the database part of the codebase.  Currently if a filter is done on the primary key attribute determined by `idAttribute`, it accesses the `itemsById` structure instead of scanning the collection.

There, with the addition of this feature, we could check if any indexed fields are present in a filter clause. If so, we use the index to perform the filter. This way everybody benefits from the feature in their application code by adding `attr({ isUnique: true })` to fields :)

Let me know what you think!

**Comment by Elijen** [comment]
Thanks for all the info @tommikaikkonen. I was bit busy but will try to implement something this week. I need to migrate my app to 0.9 first, though :)

**Comment by Elijen** [comment]
> Specifically Map would allow to index complex values without implementing a hash function ourselves.
I used simple JavaScript object for now as `immutable-ops` does not seem to support `Map`.

There is a small problem with indexing `null` values as it's converted to `String` meaning `index[null] === index["null"]`. So either we don't index `null` values at all, document the behaviour or find a different way to index it.

**Comment by Elijen** [comment]
I figured there is no big benefit of using custom indexes on client side if you use `PureComponent`s or proper implementation of `shouldComponentUpdate`. I am also not using Redux anymore, so I will close this issue.
