### ISSUE TITLE
Creating selector

### ISSUE THREAD

**Issue by BrunoQuaresma** [tommikaikkonen/redux-orm#85]
I try use this selector but without success

```
import { createSelector } from 'redux-orm'

export const getUser = orm => createSelector(orm, session => {
  if (session.User.exists()) {
    return session.User.first().withRefs
  }
})()
```

```
const mapStateToProps = state => {
  return {
    root: state.root,
    user: getUser(orm)
  }
}
```

The error is.:

> AppDrawer.js:45 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined

**Comment by vamsiampolu** [comment]
To create a selector, first take the state which is managed by `redux-orm`:

```js

const stateSelector = state => {
  return state.orm;
}

const propsSelector = (state, props) => props

const inputSelectors = [ stateSelector, propsSelector]

//result is computed from session and props
const transformFn = (session, props) => {
   return !!session.User.first().userId;
}

var sessionSelector = createSelector(inputSelector, transformFn);
```

redux-orm instantiates a session from the return value of the first input selector, the other input selectors can return other pieces of state (or props). You can query the orm for the user in the transform function as usual.

Since you are selecting a single user, use `.ref` instead of `.withRefs`, in cases where you have multiple selections, use `.toRefArray` and `.toModelArray` instead of `.withRefs` if using `0.9`
